version: '3.8'

services:
  server:
    build: ./ips-server
    image: ips-server:latest
    volumes:
      - ./results/server:/results:rw
    hostname: ips-server
    networks:
      - intnet
    expose:
      - "50001"
    command: iperf3 --server --port 50001 --daemon --json --logfile /results/server/iperf3.log && wait 70 && exit

  client-tcp:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results:rw
    hostname: ips-client-tcp
    networks:
      - intnet
    command: iperf3 --client ips-server --port 50001 --reverse --parallel 5 --time 60 --logfile /results/client/tcp-iperf3.log

  client-udp:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results:rw
    hostname: ips-client-udp
    networks:
      - intnet
    command: iperf3 --client ips-server --port 50001 --udp --reverse --parallel 5 --time 60 --logfile /results/client/udp-iperf3.log
