version: '3.8'

services:
  server:
    build: ./ips-server
    image: ips-server:latest
    volumes:
      - ./results/server:/results:rw
    hostname: ips-server
    networks:
      - intnet
    expose:
      - "50001"
      - "50002"
    command: [ "50001", "50002" ]

  client-tcp:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results:rw
    hostname: ips-client-tcp
    networks:
      - intnet
    command: [ "50001" ]

  client-udp:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results:rw
    hostname: ips-client-udp
    networks:
      - intnet
    command: [ "50002", "--udp" ]
