version: '3.8'

networks:
  intnet:
    external: true

services:
  server:
    build: ./ips-server
    image: ips-server:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - ./results/server:/results/server:rw
    hostname: ips-server
    networks:
      - intnet
    environment:
      PORTS: "50010 50210 50220 50100"

  client-10:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results/client:rw
    hostname: ips-client-tcp
    networks:
      - intnet
    environment:
      PORT: "50010"
      INITIAL_WAIT: "0"
      TIME: "70"

  client-210:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results/client:rw
    hostname: ips-client-udp
    networks:
      - intnet
    environment:
      PORT: "50210"
      INITIAL_WAIT: "30"
      TIME: "70"

  client-220:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results/client:rw
    hostname: ips-client-udp
    networks:
      - intnet
    environment:
      PORT: "50220"
      INITIAL_WAIT: "10"
      TIME: "70"

  client-100:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results/client:rw
    hostname: ips-client-udp
    networks:
      - intnet
    environment:
      PORT: "50100"
      INITIAL_WAIT: "50"
      TIME: "30"
