version: '3.8'

networks:
  intnet:
    external: true

services:
  server:
    build: ./ips-server
    image: ips-server:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - ./results/server:/results/server:rw
    hostname: ips-server
    networks:
      - intnet
    expose:
      - "50001"
      - "50002"
    environment:
      PORTS: "50001 50002"

  client-tcp:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results/client:rw
    hostname: ips-client-tcp
    networks:
      - intnet
    environment:
      PORT: "50001"
      UDP: ""

  client-udp:
    build: ./ips-client
    image: ips-client:latest
    depends_on:
      - server
    volumes:
      - ./results/client:/results/client:rw
    hostname: ips-client-udp
    networks:
      - intnet
    environment:
      PORT: "50002"
      UDP: "--udp"
