version: '3.8'

services:
  client1:
    build: ./ips-client1
    image: ips-client1:latest
    networks: intnet
    ports: 55001:55001
    extra_hosts: "client2:10.0.1.2"
    volumes: logs:/home/root/logs

  client2:
    build: ./ips-client2
    image: ips-client2:latest
    networks: intnet
    ports: 55002:55002
    extra_hosts: "client1:10.0.1.1"

volumes:
  logs: /home/vuks/workspace/results